const languages = {
    "auto": "Detect Language",
    "en": "English 🇺🇸",
    "ta": "Tamil 🇮🇳",
    "hi": "Hindi 🇮🇳",
    "es": "Spanish 🇪🇸",
    "fr": "French 🇫🇷",
    "de": "German 🇩🇪",
    "ja": "Japanese 🇯🇵",
    "zh-CN": "Chinese 🇨🇳",
    "it": "Italian 🇮🇹",
    "pt": "Portuguese 🇵🇹",
    "ar": "Arabic 🇸🇦",
    "ru": "Russian 🇷🇺",
    "ko": "Korean 🇰🇷",
    "nl": "Dutch 🇳🇱",
    "tr": "Turkish 🇹🇷",
    "vi": "Vietnamese 🇻🇳",
    "pl": "Polish 🇵🇱",
    "sv": "Swedish 🇸🇪",
    "id": "Indonesian 🇮🇩",
    "el": "Greek 🇬🇷",
    "he": "Hebrew 🇮🇱",
    "bn": "Bengali 🇮🇳",
    "th": "Thai 🇹🇭",
    "ms": "Malay 🇲🇾"
};
